### ISSUE TITLE
Pre-built entities does not appear on "Expected Entity in Response..." field.

### ISSUE THREAD

**Issue by BelvedereHenrique** [Microsoft/ConversationLearner-Samples#189] opened 2018-05-16 15:09 UTC
When creating a new Action, pre-built entities should appear on the Entities List for the field "Expected Entity Reponse".

Entities:
![image](https://user-images.githubusercontent.com/24565006/40125625-bbc1945e-5901-11e8-87c4-c229a749794b.png)

New Action:
![image](https://user-images.githubusercontent.com/24565006/40125657-ce4ddede-5901-11e8-9d27-545f4014da53.png)

Documentation: https://docs.microsoft.com/en-us/azure/cognitive-services/labs/conversation-learner/tutorials/7-built-in-entities

**Comment by jasondwilliams** [comment] 2018-05-16 16:01
Hi @BelvedereHenrique - Thanks for reporting.  The problem here is that our doc is out of date.  Pre-built entities are read-only, and can only be set by the pre-built model that extracts them from user utterances.  The issue is that many pre-built entities include resolution (eg, mapping "today" to a canonical date); populating an entity via the "expected entity" mechanism would not do resolution, which makes it messy handling pre-built entities in code.  I'll add a task to update the doc, and close this when that's deployed.  Thanks!

**Comment by BelvedereHenrique** [comment] 2018-05-16 16:19
I get it.
Thank you!

**Comment by jasondwilliams01** [comment] 2018-05-16 20:36
I submitted a PR to update the doc -- will take a few days to get signed off and deployed.  Also updated the tutorial app.

**Comment by jasondwilliams** [comment] 2018-05-16 20:37
I submitted a PR to update the doc -- will take a few days to get signed off and deployed. Also updated the tutorial app.  Closing.

**Closed by jasondwilliams** 2018-05-16 20:37 UTC
